### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by rija8542** [CSCI-5828-Foundations-Sftware-Engr/ViewJyeS-Amazon-Price-Tracker#23]
A user should be able to log in to the website and start Ttracking, which involves designing the user interface, validating and authenticating user input, handling login errors, and ensuring the security of the login page.

**Comment by JanushiShastri2001** [comment]
Working on the template for the login page code.

**Comment by JanushiShastri2001** [comment]
Implementing and checking login details with database.
